In [1]:
"""
Created on: 18-08-2026

@author B.A. Sturre

PyTorch tutorial 
https://www.youtube.com/watch?v=c36lUUr864M 
"""

import numpy as np
import torch
import torch.nn as nn

## Softmax

In [2]:
# S(y_i) = \f{e^{y_i}}{\sum_j e^{y_j}} \in (0, 1)
def softmax(x): 
    return np.exp(x) / np.sum(np.exp(x), axis=0)

x = np.array([2.0, 1.0, 0.1])
outputs = softmax(x)
print(f'softmax numpy: {outputs}')

softmax numpy: [0.65900114 0.24243297 0.09856589]


In [3]:
x = torch.tensor([2.0, 1.0, 0.1])
outputs = x.softmax(dim=0)  # dim = axis = 0
print(outputs)

tensor([0.6590, 0.2424, 0.0986])


A lot of times the Softmax loss is combined with the so-called cross-entropy loss. This measures the performance of our classification model whose output is a probability between 0 and 1. It can be used in multiclass problems. The loss increases as the predicted probability diverges from the actual label: the better our prediction the lower our loss. 

## Cross-Entropy loss

In [4]:
# D(\hat{y}, y) = -\f{1}{N} \sum_i y_i \log(\hat{y}_i)
def cross_entropy(actual, predicted): 
    loss = -np.sum(actual * np.log(predicted))
    return loss 

y = np.array([1, 0, 0])

y_pred_good = np.array([0.7, 0.2, 0.1])
y_pred_bad = np.array([0.1, 0.3, 0.6])

l1 = cross_entropy(y, y_pred_good)
l2 = cross_entropy(y, y_pred_bad)

print(f'Loss good: {l1:.4f}')
print(f'Loss bad: {l2:.4f}')

Loss good: 0.3567
Loss bad: 2.3026


In [5]:
loss = nn.CrossEntropyLoss()

y = torch.tensor([0])

y_pred_good = torch.tensor([[2.0, 1.0, 0.1]])  # size n_samples x n_classes = 1x3
y_pred_bad = torch.tensor([[0.5, 2.0, 0.3]])

l1 = loss(y_pred_good, y)
l2 = loss(y_pred_bad, y)

print(f'Loss good: {l1.item():.4f}')
print(f'Loss bad: {l2.item():.4f}')

Loss good: 0.4170
Loss bad: 1.8406


Getting the actual predictions

In [6]:
_, predictions1 = torch.max(y_pred_good, 1)
_, predictions2 = torch.max(y_pred_bad, 1)
print(predictions1)
print(predictions2)

tensor([0])
tensor([1])


We can also increase the number of samples 

In [7]:
loss = nn.CrossEntropyLoss()

# 3 samples 
y = torch.tensor([2, 0, 1])

y_pred_good = torch.tensor([[0.1, 1.0, 2.1],[2.0, 1.0, 0.1], [0.1, 3.0, 0.1]])  # size n_samples x n_classes = 3x3
y_pred_bad = torch.tensor([[2.5, 1.0, 0.3], [0.1, 2.0, 0.3], [0.5, 2.0, 0.3]])

l1 = loss(y_pred_good, y)
l2 = loss(y_pred_bad, y)

print(f'Loss good: {l1.item():.4f}')
print(f'Loss bad: {l2.item():.4f}')

Loss good: 0.3018
Loss bad: 1.6719


Binary classification

In [8]:
class NeuralNet1(nn.Module): 
    def __init__(self, input_size, hidden_size): 
        super(NeuralNet1, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()  # activation function 
        self.linear2 = nn.Linear(hidden_size, 1)

    def forward(self, x): 
        out = self.linear1(x)
        out = self.relu(x)
        out = self.linear2(x)
        y_pred = torch.sigmoid(out)
        return y_pred

model = NeuralNet1(input_size=28*28, hidden_size=5)
criterion = nn.BCELoss()

Multi-class classifciation

In [9]:
class NeuralNet2(nn.Module): 
    def __init__(self, input_size, hidden_size, num_classes): 
        super(NeuralNet2, self).__init__()
        self.linear1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()  # activation function 
        self.linear2 = nn.Linear(hidden_size, num_classes)

    def forward(self, x): 
        out = self.linear1(x)
        out = self.relu(x)
        out = self.linear2(x)
        return out 

model = NeuralNet2(input_size=28*28, hidden_size=5, num_classes=3)
criterion = nn.CrossEntropyLoss()