In [32]:
"""
Created on: 18-08-2026

@author B.A. Sturre

PyTorch tutorial 
https://www.youtube.com/watch?v=c36lUUr864M 
"""

import math
import numpy as np
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader

## Dataset and DataLoader

Optimizing model based on whole dataset might be very time consuming. A better way for large datasets is to divide the dataset into so-called *batches*, and then you loop over epochs and then over the number of total batches. Then you get the `x_batch` and `y_batch` samples and do the optimization only over those batches. PyTorch can do that using `DataLoader`. 

Definitions: 
    - epoch: 1 forward and backward pass of ALL training samples
    - `batch_size`: number of training samples in one forward \& backward pass
    - number of iterations: number of passes, each pass using `batch_size` number of samples (ex: 100 samples with `batch_size` = 20 $\rightarrow$ $100/20=5$ iterations per epoch)


We have the wine dataset from the tutorial (https://www.youtube.com/watch?v=c36lUUr864M, to find at https://github.com/patrickloeber/pytorchTutorial/blob/master/data/wine/wine.csv). The first row is a header. We want to predict the wine categories (1, 2 or 3), and the class label is in the very first column. All the other columns are the features. 

In [33]:
# impement our own custom dataset 
class WineDataset(Dataset):

    def __init__(self):
        # data loading 
        xy = np.loadtxt('wine.csv', delimiter=',', dtype=np.float32, skiprows=1)
        self.x = torch.from_numpy(xy[:, 1:])
        self.y = torch.from_numpy(xy[:, [0]])  # n_samples, 1
        self.n_samples = xy.shape[0]

    def __getitem__(self, index):
        return self.x[index], self.y[index]

    def __len__(self):
        return self.n_samples

dataset = WineDataset()
first_data = dataset[0]
features, labels = first_data
print(features, labels)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [34]:
batch_size = 4

dataset = WineDataset()
dataloader = DataLoader(dataset=dataset, batch_size=batch_size, shuffle=True, num_workers=2)  # shuffle = True useful for training, 
                                    #increasing num_workers might make it faster since it's using multiple subprocesses now

datatiter = iter(dataloader)
data = next(datatiter)
features, labels = data 
print(features, labels)

tensor([[1.4100e+01, 2.0200e+00, 2.4000e+00, 1.8800e+01, 1.0300e+02, 2.7500e+00,
         2.9200e+00, 3.2000e-01, 2.3800e+00, 6.2000e+00, 1.0700e+00, 2.7500e+00,
         1.0600e+03],
        [1.2850e+01, 1.6000e+00, 2.5200e+00, 1.7800e+01, 9.5000e+01, 2.4800e+00,
         2.3700e+00, 2.6000e-01, 1.4600e+00, 3.9300e+00, 1.0900e+00, 3.6300e+00,
         1.0150e+03],
        [1.3730e+01, 1.5000e+00, 2.7000e+00, 2.2500e+01, 1.0100e+02, 3.0000e+00,
         3.2500e+00, 2.9000e-01, 2.3800e+00, 5.7000e+00, 1.1900e+00, 2.7100e+00,
         1.2850e+03],
        [1.2600e+01, 2.4600e+00, 2.2000e+00, 1.8500e+01, 9.4000e+01, 1.6200e+00,
         6.6000e-01, 6.3000e-01, 9.4000e-01, 7.1000e+00, 7.3000e-01, 1.5800e+00,
         6.9500e+02]]) tensor([[1.],
        [1.],
        [1.],
        [3.]])


In [35]:
# dummy training loop 
num_epochs = 2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples / batch_size)
print(total_samples, n_iterations)

for epoch in range(num_epochs):
    for i, (inputs, labels) in enumerate(dataloader):
        # forward, backward, update
         
        if (i+1) % 5 == 0: 
            print(f'epoch {epoch+1}, step {i+1}/{n_iterations}, inputs {inputs.shape}')

178 45
epoch 1, step 5/45, inputs torch.Size([4, 13])
epoch 1, step 10/45, inputs torch.Size([4, 13])
epoch 1, step 15/45, inputs torch.Size([4, 13])
epoch 1, step 20/45, inputs torch.Size([4, 13])
epoch 1, step 25/45, inputs torch.Size([4, 13])
epoch 1, step 30/45, inputs torch.Size([4, 13])
epoch 1, step 35/45, inputs torch.Size([4, 13])
epoch 1, step 40/45, inputs torch.Size([4, 13])
epoch 1, step 45/45, inputs torch.Size([2, 13])
epoch 2, step 5/45, inputs torch.Size([4, 13])
epoch 2, step 10/45, inputs torch.Size([4, 13])
epoch 2, step 15/45, inputs torch.Size([4, 13])
epoch 2, step 20/45, inputs torch.Size([4, 13])
epoch 2, step 25/45, inputs torch.Size([4, 13])
epoch 2, step 30/45, inputs torch.Size([4, 13])
epoch 2, step 35/45, inputs torch.Size([4, 13])
epoch 2, step 40/45, inputs torch.Size([4, 13])
epoch 2, step 45/45, inputs torch.Size([2, 13])


In [36]:
# dummy training loop 
num_epochs = 2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples / batch_size)
print(total_samples, n_iterations)

for epoch in range(num_epochs):
    for i, (inputs, labels) in enumerate(dataloader):
        # forward, backward, update
         
        if (i+1) % 5 == 0: 
            print(f'epoch {epoch+1}, step {i+1}/{n_iterations}, inputs {inputs.shape}')

178 45
epoch 1, step 5/45, inputs torch.Size([4, 13])
epoch 1, step 10/45, inputs torch.Size([4, 13])
epoch 1, step 15/45, inputs torch.Size([4, 13])
epoch 1, step 20/45, inputs torch.Size([4, 13])
epoch 1, step 25/45, inputs torch.Size([4, 13])
epoch 1, step 30/45, inputs torch.Size([4, 13])
epoch 1, step 35/45, inputs torch.Size([4, 13])
epoch 1, step 40/45, inputs torch.Size([4, 13])
epoch 1, step 45/45, inputs torch.Size([2, 13])
epoch 2, step 5/45, inputs torch.Size([4, 13])
epoch 2, step 10/45, inputs torch.Size([4, 13])
epoch 2, step 15/45, inputs torch.Size([4, 13])
epoch 2, step 20/45, inputs torch.Size([4, 13])
epoch 2, step 25/45, inputs torch.Size([4, 13])
epoch 2, step 30/45, inputs torch.Size([4, 13])
epoch 2, step 35/45, inputs torch.Size([4, 13])
epoch 2, step 40/45, inputs torch.Size([4, 13])
epoch 2, step 45/45, inputs torch.Size([2, 13])


Famous datasets are sometimes already loaded in PyTorch

In [37]:
#torchvision.datasets.MNIST()
# or fashion-mnist, cifar, coco

## Transforms for Datasets

We add a transform in the dataset

In [38]:
# impement our own custom dataset 
class WineDataset(Dataset):

    def __init__(self, transform=None ):
        # data loading 
        xy = np.loadtxt('wine.csv', delimiter=',', dtype=np.float32, skiprows=1)
        self.x = xy[:, 1:]
        self.y = xy[:, [0]] # n_samples, 1
        self.n_samples = xy.shape[0]

        self.transform = transform

    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform: 
            sample = self.transform(sample)
        return sample 

    def __len__(self):
        return self.n_samples

We will create our own transform classes, i.e. to transform it to a tensor

In [42]:
class ToTensor:
    def __call__(self, sample): 
        inputs, targets = sample 
        return torch.from_numpy(inputs), torch.from_numpy(targets)

dataset = WineDataset(transform=None)
first_data = dataset[0]
features, labels = first_data
print(features)
print(type(features), type(labels))

dataset = WineDataset(transform=ToTensor())
first_data = dataset[0]
features, labels = first_data
print('\n', features)
print(type(features), type(labels))

[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
 2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>

 tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])
<class 'torch.Tensor'> <class 'torch.Tensor'>


we can also compose two transforms: 

In [43]:
class MulTransform: 
    def __init__(self, factor):
        self.factor = factor 

    def __call__(self, sample): 
        inputs, target = sample 
        inputs *= self.factor 
        return inputs, target 

factor = 2
composed = torchvision.transforms.Compose([ToTensor(), MulTransform(factor)])
dataset = WineDataset(transform=composed)

first_data = dataset[0]
features, labels = first_data
print(features)
print(type(features), type(labels))

tensor([2.8460e+01, 3.4200e+00, 4.8600e+00, 3.1200e+01, 2.5400e+02, 5.6000e+00,
        6.1200e+00, 5.6000e-01, 4.5800e+00, 1.1280e+01, 2.0800e+00, 7.8400e+00,
        2.1300e+03])
<class 'torch.Tensor'> <class 'torch.Tensor'>
