In [1]:
"""
Created on: 17-08-2026

@author B.A. Sturre

PyTorch tutorial 
https://www.youtube.com/watch?v=c36lUUr864M 
"""

import numpy as np 
import torch

## Tensors

In [2]:
# creating an empty tensor 
size = 3
x = torch.empty(size)
print(x)

size = (2, 3)
x = torch.empty(size)
print(x)

# creating tensor with random values 
x = torch.rand(size)
print(x)

# creating tensor with zeros/ones
x = torch.zeros(size)
print(x)
x = torch.ones(size)
print(x)

tensor([-1.4056e+17,  3.6134e-41,  0.0000e+00])
tensor([[-1.2602e+17,  3.6134e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[0.5832, 0.5063, 0.2027],
        [0.5461, 0.9493, 0.5047]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


The default datatype for a PyTorch tensor is `float32`, but we can also assign it a different datatype: 

In [3]:
x = torch.ones(size)
print(x, x.dtype)

x = torch.ones(size, dtype=int)  # or float16, double, float32
print(x, x.dtype)

# seeing size
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]]) torch.int64
torch.Size([2, 3])


making tensor from list

In [4]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


basic operations

In [5]:
x, y = torch.rand(2, 2), torch.rand(2, 2)

print(x, '\n', y)

print('\naddition')
z = x + y 
print(z)
z = torch.add(x, y)
print(z)

# add elements of x to y
print('\nadding elements')
y.add_(x)
print(y)

# subtracting 
z = x - y 
z = torch.sub(x, y)
y.sub_(x)

# element wise multiplication 
z = x * y
z = torch.mul(x, y)
y.mul_(x)

# element wise division
z = x / y
z = torch.div(x,y)
y.div_(x)

tensor([[0.9626, 0.6623],
        [0.1444, 0.8575]]) 
 tensor([[0.4282, 0.1106],
        [0.0566, 0.7277]])

addition
tensor([[1.3908, 0.7729],
        [0.2010, 1.5852]])
tensor([[1.3908, 0.7729],
        [0.2010, 1.5852]])

adding elements
tensor([[1.3908, 0.7729],
        [0.2010, 1.5852]])


tensor([[0.4282, 0.1106],
        [0.0566, 0.7277]])

indexing and reshaping

In [6]:
x = torch.rand(5, 3) 
print(x)

# rows, columns
print(x[:, 0])

print(x[1, :])

# for tensor with one element to get actual value
print(x[1, 1])
print(x[1, 1].item())

tensor([[0.6084, 0.4774, 0.6781],
        [0.1948, 0.2707, 0.0913],
        [0.3223, 0.9149, 0.0468],
        [0.8539, 0.8996, 0.6140],
        [0.1889, 0.1602, 0.5033]])
tensor([0.6084, 0.1948, 0.3223, 0.8539, 0.1889])
tensor([0.1948, 0.2707, 0.0913])
tensor(0.2707)
0.27072566747665405


In [7]:
x = torch.rand(4, 4)

# reshaping
y = x.view(16)  # number of elements must be the same
print(y)

y = x.view((4, 4))
print(y)

# automatically determining right size
y = x.view(-1, 8)
print(y.shape)
print(y.size())

tensor([0.2923, 0.3950, 0.9028, 0.4282, 0.9389, 0.4492, 0.5170, 0.0351, 0.8752,
        0.9644, 0.9160, 0.9696, 0.0508, 0.5646, 0.3234, 0.4352])
tensor([[0.2923, 0.3950, 0.9028, 0.4282],
        [0.9389, 0.4492, 0.5170, 0.0351],
        [0.8752, 0.9644, 0.9160, 0.9696],
        [0.0508, 0.5646, 0.3234, 0.4352]])
torch.Size([2, 8])
torch.Size([2, 8])


converting to/from numpy

In [8]:
# tensor to numpy
a = torch.ones(5)
print(a.type())
b = a.numpy()
print(type(b))

# numpy to tensor
a = np.ones(5)
print(type(a))
b = torch.from_numpy(a)
print(b.type())

# if tensor is on CPU and not on the GPU,, both objects are on the same memory slice 
# so changing one also changes the other: 
b[1] = 2
print(a)
print(b)

# solution: 
print('\nsolution')
a = torch.ones(5)
b = a.clone().numpy()

b[1] = 2
print(a)
print(b)

a = np.ones(5)
b = torch.from_numpy(a).clone()

b[1] = 2
print(a)
print(b)

torch.FloatTensor
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
torch.DoubleTensor
[1. 2. 1. 1. 1.]
tensor([1., 2., 1., 1., 1.], dtype=torch.float64)

solution
tensor([1., 1., 1., 1., 1.])
[1. 2. 1. 1. 1.]
[1. 1. 1. 1. 1.]
tensor([1., 2., 1., 1., 1.], dtype=torch.float64)


`requires_grad`: by default `False`, if `True` it tells PyTorch that it will need to calculate the gradient of the tensor later in the optimization steps. 

In [9]:
x = torch.ones(5, requires_grad=True)